name: xat
description: A new Flutter project.
# 下面的行使用flutter pub发布防止包意外发布到pub.dev。这是私有包的首选。
publish_to: 'none' # 如果您希望发布到 pub.dev，请删除此行

# 下面定义了应用程序的版本和内部版本号。版本号是三个用点分隔的数字，如1.2.43，后跟一个用+分隔的可选内部版本号。
# 在flutter build中，可以通过分别指定--build-name和--build-number来覆盖版本和构建器编号。
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

# 依赖关系指定了您的软件包需要的其他软件包，以便工作。
# 要自动升级你的软件包的依赖关系到最新版本，可以考虑运行 `flutter pub upgrade --major-versions`。
# 另外，可以通过改变下面的版本号来手动更新依赖的软件包到pub.dev上的最新版本。
# 要查看哪些依赖有更新的版本，请运行 `flutter pub outdated`。
dependencies:
  flutter:
    sdk: flutter

  # 下面将库比蒂诺Icons字体添加到您的应用程序中。
  # 与CupertinoIcons类一起用于iOS样式图标。
  cupertino_icons: ^1.0.2
  # 状态管理
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.3.2
  # openai_api 封装的 api
  openai_api: ^0.0.4+3
  # 本地环境变量
  envied: ^0.3.0+3
  logger: ^1.4.0
  uuid: ^3.0.7
  pull_to_refresh: ^2.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  markdown_widget: ^2.1.0
  flutter_math_fork: ^0.7.1
  markdown: ^7.0.2
  floor: ^1.4.1
  riverpod_annotation: ^2.0.1
  go_router: ^8.0.0
  tiktoken: ^1.0.3
  collection: ^1.17.1
  record: ^4.4.4
  flutter_svg: ^2.0.6
  localstorage: ^4.0.1+2
  quickalert: ^1.0.1
  screenshot: ^2.1.0
  file_picker: ^5.3.2
  share_plus: ^7.0.2
  # 国际化
  flutter_localizations:
    sdk: flutter
  intl: any
  tuple: ^2.0.1
  # 网络请求
  dio: ^5.2.0+1
  pretty_dio_logger: 1.3.1
  connectivity_plus: 4.0.1
  # 弹窗
  flutter_easyloading: ^3.0.3
  flash: ^3.0.5+1
  # shared_preferences
  shared_preferences: ^2.1.2
  # 数据库ORM
  sqflite: ^2.2.8+4
  drift: any
  sqlite3_flutter_libs: any
  path_provider: any
  path: ^1.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # 下面的 "flutter_lints "包包含一组推荐的提示，以鼓励良好的编码实践。
  # 该包提供的lint集在位于你的包根部的`analysis_options.yaml`文件中被激活。
  # 关于停用特定的lint规则和激活其他规则的信息，请参见该文件。
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0
  freezed: ^2.3.2
  json_serializable: ^6.6.2
  floor_generator: ^1.4.1
  flutter_gen_runner:
  # riverpod
  build_runner: ^2.3.3
  custom_lint:
  riverpod_lint: ^1.1.5
  riverpod_generator: ^2.1.3
  drift_dev: any



  # 关于这个文件的通用Dart部分的信息，请参见以下页面：https://dart.dev/tools/pub/pubspec

  # 以下部分是专门针对Flutter包的。
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # 国际化
flutter_intl:
  enabled: true

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

